name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Minikube
        run: |
          minikube start
          minikube kubectl -- apply -f ./nginx-deployment.yaml

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Deploy nginx with Helm
        run: |
          helm upgrade --install my-nginx ./my-nginx-chart --namespace default --force

  deploy-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Minikube
        run: |
          minikube start
          kubectl apply -f ./secret.yaml

      - name: Verify secrets deployment
        run: |
          kubectl get secrets my-secret
